add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})
set_languages("cxx17")
add_requires("fmt")
target("struct")
    set_kind("binary")
    add_files("struct.cpp")
    add_packages("fmt")
    set_rundir("$(projectdir)")

target("optional")
    set_kind("binary")
    add_files("optional.cpp")
    add_packages("fmt")
    set_rundir("$(projectdir)")